server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /ops-api/ {
    proxy_pass https://phan-mem-ban-hang-online-api.fly.dev/api/v1/;
    proxy_http_version 1.1;
    proxy_ssl_server_name on;
    proxy_set_header Host phan-mem-ban-hang-online-api.fly.dev;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Cookie $http_cookie;
    proxy_pass_header Set-Cookie;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
